### ISSUE TITLE
Suggestion: Make it culinary construct style.

### ISSUE THREAD

**Issue by Darkmega18** [Tiviacz1337/PizzaCraft#92] opened 2023-04-25 23:40 UTC
https://www.curseforge.com/minecraft/mc-mods/culinary-construct
Basically, use your pizza doughs as a base. and allow any simple food items, within a certain hunger fulfilling range be used on pizza to make whacky custom pizzas.

Alternatively you could use tags and use code to get the color of the ingredient when using it. For example theres tomato sauce in a number of mods, likely in harvestcraft, vanilla food pantry and farmers delight etc. 
Someone should be able to tag sauces and such as "pizza sauces" and people can use them as a sauce in their pizza, same with ingredients if you don't want to fully allow just complete pizza anarchy like the meals and sandwiches from culinary construct.

Speaking of farmers delight, there are a few objects from farmers delight you could very likely just integrate as compatibility if it exists and hide your own. such as knives, the chopping board, the grill being useable as an oven perhaps etc. it makes for a fair bit of feature multiplication for packs wanting to include more foods etc.

**Comment by Tiviacz1337** [comment] 2023-07-17 13:14
PizzaCraft is going to have overhaul similar to your suggestion, I'm just creating sheet to collect all ideas and thinking about cool way to implement it

**Comment by Darkmega18** [comment] 2023-07-17 17:39
Ooooh, wonderful. keep me posted perhaps? definitely interested.

**Comment by Tiviacz1337** [comment] 2023-07-31 21:29
https://legacy.curseforge.com/minecraft/mc-mods/pizzacraft/files/all
here's the release for 1.20.1, you can share your further ideas

**Comment by Darkmega18** [comment] 2023-07-31 23:07
oh no. I play 1.19.2 still. D:
Any chance of a feature backport? :< 
I may still get into it and try how it looks sometime, but I'm working on some modpack stuff currently...

**Comment by Tiviacz1337** [comment] 2023-07-31 23:40
yeah, I'm working on backport, althrough I plan backporting to 1.18.2 and 1.19.4

**Comment by Tiviacz1337** [comment] 2023-08-01 12:42
nvm I backported to 1.19.2 too

**Comment by Darkmega18** [comment] 2023-08-01 21:35
OWO
amazing. I shall give it a go when I see it's posted. :D

**Comment by Tiviacz1337** [comment] 2023-08-01 23:56
https://legacy.curseforge.com/minecraft/mc-mods/pizzacraft/files

**Comment by Darkmega18** [comment] 2023-08-02 07:53
oops! pizza doesn't retain it's texture when cutting it! D: so after the first cut, the pizza topping colors disappear leaving a blank pizza. the slices still retain the right food when coming off, it's just visuals so far.

I also tried adding a food item that has a built in potion effect (some farmers respite tea...), and using a potion as the sauce (normal fire resistance) for the pizza. the pizza visibly says fire resistance 3 from the sauce, but I only get the resistance from the tea I put inside the pizza itself. 
(it was like. "fiery meat feast + mozzarella infused with resistance tea" pizza. very whack. I do enjoy.)

Would be nice to have a pizza renaming box above in the table so you can title the pizza and have it be retained when moving it around and on the slices themselves? :) as an additional when you refine the system further.


a decorative item unrelated to the new mechanics I just thought of could also be maybe a pizza box? made with 8 paper in a circle like a chest?
it's a simple white pizza box but perhaps you can texture the top with a banner (doesn't consume the banner, just applies a texture similar to it).
it only takes pizza in it's slot and you can open and close the pizza box to display it with shift rightclick, and rightclicking while it's open will take a slice out and put it in your hand.
+the ability to break it quickly and pick it up like the pizza delivery bag.

Tags for dough types that are compatible? alternatively just allow any "forge:dough?" to be used in that slot? (visually still makes the same pizza, but might add filling value to the pizza also?)

While on the topic of tags. Add your knives to:
farmersdelight:tools/knives . they'll then also be added through that tag to straw_harvesters so your knives can be used like theirs.

Finally, seems you can still attempt to make pizza the old way, with rolling out the dough with the rolling pin then placing it down. Intended?

I may have also just crashed my game because it picked up the pizza with carry on. forgot to blacklist. X_X
Here is the related crash report: 
[crash-2023-08-02_18.22.46-client.txt](https://github.com/Tiviacz1337/PizzaCraft/files/12237866/crash-2023-08-02_18.22.46-client.txt)

**Comment by Darkmega18** [comment] 2023-08-02 10:37
Here is also a zipped folder you can put into your mod that has some cutting recipes in a datapack for your items so they work with the cutting boards for farmers delight. they're all conditioned to only load if it's actually loaded. I put wings over the original chicken cutting recipes they have so you get wings off the chicken when cut up.
and then repurposed their cooked ham to give your ham, while cooked porkchops not used by them can also be cut up for ham (and just hope there won't be too many pedantic people). while leaving bacon when the pork is uncooked.

all the rest of the veges just cut down into 2 items for each and are forge dictionaried also, so they should work via other mod's similar crops as long as they're tagged too. with the cheese cutting into 3 like your mod does.
A lot of people probably use farmers delight, and yours follow similar mechanics. so, saves an extra chopping block for specifically your things being needed.
[pizzacraft for delightful farmers.zip](https://github.com/Tiviacz1337/PizzaCraft/files/12239132/pizzacraft.for.delightful.farmers.zip)

**Comment by Tiviacz1337** [comment] 2023-08-02 11:07
In my dev environment pizza retain it's textures when I cut or eat it. Any steps how to reproduce?

I've noticed the potion effect is not being applied, so it'll be fixed in the next update

Naming - Probably will be added 

pizza box - probably wont be added

will do tags for dough

will do tags for knives

Yes this is intentional, as I didn't want to completely abandon idea of immersive pizza making

crash with carry on - should be reported to carry on authors too, I've replaced my call on this method to not crash, but ideally carry on mod should call IForgeBakedModel::getQuads with empty model data to prevent this

I'll add your datapack, thanks for help

**Comment by Darkmega18** [comment] 2023-08-02 12:12
> In my dev environment pizza retain it's textures when I cut or eat it. Any steps how to reproduce?

I'll have to check again, but it might be when I went to cut the pizza with a knife to get a slice off rather than eat it directly? but I'll take a quick look when I get back in. see if any errors come up or anything.
otherwise it might be a modpack related issue. >_<'

edit:
yeah, theres no issues coming up, seemingly. but the pizza slices themselves retain their sprite it seems. odd... I don't know where to point fingers other than potentially rubidium related or flywheel+occulus? could you test those? since those would have something to do with in world rendering.

**Comment by Darkmega18** [comment] 2023-08-02 12:18
as for the sauce. I just noticed the pizza that pops out of the table, and also when placed down again, doesn't retain it's sauce. even thought it retains the information on it. could that be the cause of the sauce not working?

**Comment by Tiviacz1337** [comment] 2023-08-02 12:21
that's strange in my dev environment sauce is not dissapearing, could you record a video of it? Like when you cut pizza or with this sauce issue>?

**Comment by Tiviacz1337** [comment] 2023-08-02 12:22
and no, sauce wasn't working because of other issue, I've already fixed it in my dev environment

**Closed as completed** 2023-08-04 11:56 UTC
Labels: enhancement
